### ISSUE TITLE
Autodetect the browsers to support

### ISSUE THREAD

**Issue by dunglas** [dbrekelmans/browser-driver-installer#13]
It could be nice to install all drivers for all installed browsers by default (`php install`). It would help, at least with Panther, to run the same test suite with different browsers.

Also, maybe can the command name be a bit more explicit? Such as `php vendor/bin/install-browser-drivers`?

**Comment by dbrekelmans** [comment]
Good idea; finding installed browsers and automatically installing drivers for them is something I definitely want to support in a later version.

Regarding the command name: I'm still looking at the best way to deploy a PHAR with composer.
Ideally it would put the PHAR in `vendor/bin` so you could run `vendor/bin/bdi driver:chrome` or `vendor/bin/browser-driver-installer driver:chrome`
