### ISSUE TITLE
Browser is not detected on Alpine

### ISSUE THREAD

**Issue by oleg-andreyev** [dbrekelmans/browser-driver-installer#61]
```Dockerfile
FROM php:8.1-alpine
WORKDIR /app
RUN apk add libzip-dev $PHPIZE_DEPS
RUN pecl install xdebug && docker-php-ext-enable xdebug
RUN docker-php-ext-install bcmath zip

COPY --from=phpbuild /app/vendor /app/vendor
COPY --from=jsbuild /app/public/build /app/public/build

# Chromium and ChromeDriver
ENV PANTHER_NO_SANDBOX 1
# Not mandatory, but recommended
ENV PANTHER_CHROME_ARGUMENTS='--disable-dev-shm-usage'
RUN apk add --no-cache chromium 

CMD tail -f /dev/null
```

Browser will be installed as `chromium-browser` not `chromium`.
Adding `ln -s $(which chromium-browser) /usr/bin/chromium` after install fixes the issue

**Comment by dbrekelmans** [comment]
Hi @oleg-andreyev, thanks for the report!

BDI is currently not that smart about finding the executable path of the browser: https://github.com/dbrekelmans/browser-driver-installer/blob/main/src/Browser/Chromium/PathResolver.php.

There is an option you can pass to the command with a custom path to the executable (so you wouldn't have to rename/symlink it on your system): https://github.com/dbrekelmans/browser-driver-installer/blob/main/src/Command/BrowserCommand.php#L75

Feel free to open a PR that adds this specific support for the default `chromium-browser` name on alpine! Let me know if you need any pointers on that.

**Comment by dbrekelmans** [comment]
Hi @oleg-andreyev, did this solve your issue?
