### ISSUE TITLE
Support Chromedriver Mac ARM

### ISSUE THREAD

**Issue by dbrekelmans** [dbrekelmans/browser-driver-installer#67]
Mac ARM now has its own chromedriver binary in `chromedriver_mac_arm64.zip`. The easiest way to support this is to add `MacARM` as a new operating system

**Comment by peter279k** [comment]
Just notice that these results about PHP_OS and `php_uname('m')` in the MAC M1:

![image](https://github.com/dbrekelmans/browser-driver-installer/assets/9021747/af051eae-f5c7-475e-a629-33521e60dea0)
