### ISSUE TITLE
browser:google-chrome will not work for v115+

### ISSUE THREAD

**Issue by storm1er** [dbrekelmans/browser-driver-installer#73]
The delivery process for chrome has changed

https://chromedriver.chromium.org/

![image](https://github.com/dbrekelmans/browser-driver-installer/assets/9821946/ae533268-e40d-4ba5-a6b2-83d3a1a7b77a)

More info:
- Google announcement (June) https://googlechromelabs.github.io/chrome-for-testing/
- Availability page https://googlechromelabs.github.io/chrome-for-testing/
- New endpoint to downloads chromedriver for v115+ https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json

**Comment by yblatti** [comment]
Can confirm that BDI fails with chrome from today

**Comment by Gurdarrag** [comment]
Hello @dbrekelmans ,

Here is a PR whith the new JSON endpoint system for chromedriver,

https://github.com/dbrekelmans/browser-driver-installer/pull/75

**Comment by dbrekelmans** [comment]
Could you retry with [1.0.5-beta.3](https://github.com/dbrekelmans/bdi/releases/tag/1.0.5-beta.3)?

**Comment by ajgarlag** [comment]
> Could you retry with [1.0.5-beta.3](https://github.com/dbrekelmans/bdi/releases/tag/1.0.5-beta.3)?

It worked for me. Thanks.

**Comment by dbrekelmans** [comment]
Solved with [1.0.5](https://github.com/dbrekelmans/browser-driver-installer/releases/tag/1.0.5), thanks everyone who was involved!
