### ISSUE TITLE
CI: RateLimit for GitHub API

### ISSUE THREAD

**Issue by Chris53897** [dbrekelmans/browser-driver-installer#83]
Many CI runs fail, because of the RateLimit for GitHub API.
 Maybe someone can help with this problem. 
 
```
 HTTP/1.1 403 rate limit exceeded returned for "https://api.github.com/repos  
  /mozilla/geckodriver/releases/latest".               
```

**Comment by dbrekelmans** [comment]
Hi @Chris53897, thanks for the report. This is a known issue, duplicate of https://github.com/dbrekelmans/browser-driver-installer/issues/70
