### ISSUE TITLE
Unit tests: ChromeDriver

### ISSUE THREAD

**Issue by dbrekelmans** [dbrekelmans/browser-driver-installer#9]
We need unit tests for:
- `DBrekelmans\BrowserDriverInstaller\Driver\ChromeDriver\Downloader`
- `DBrekelmans\BrowserDriverInstaller\Driver\ChromeDriver\VersionResolver`

**Comment by laurent35240** [comment]
Hi,

Here #31 is pull request for Chrome Driver unit tests.
With previous pull request we should have a decent code coverage now
